#!/bin/bash
# GitHub Upload Instructions for SoftwareRouter
# 
# This script contains commands to push your SoftwareRouter project to GitHub
# Follow these steps:

echo "========================================="
echo "GitHub Upload Guide for SoftwareRouter"
echo "========================================="
echo ""
echo "STEP 1: Create GitHub Repository"
echo "---------------------------------"
echo "1. Go to: https://github.com/new"
echo "2. Repository name: SoftwareRouter"
echo "3. Description: Full-featured Linux software router with IDS/IPS"
echo "4. Choose: Public or Private"
echo "5. DO NOT initialize with README, .gitignore, or license (we already have them)"
echo "6. Click 'Create repository'"
echo ""
echo "STEP 2: Get Your GitHub Username"
echo "---------------------------------"
echo "Replace 'YOUR_GITHUB_USERNAME' below with your actual GitHub username"
echo ""
echo "STEP 3: Run These Commands"
echo "---------------------------------"
echo ""
echo "# Set the remote repository (replace YOUR_GITHUB_USERNAME)"
echo "git remote add origin https://github.com/YOUR_GITHUB_USERNAME/SoftwareRouter.git"
echo ""
echo "# Push to the Dev branch"
echo "git push -u origin Dev"
echo ""
echo "========================================="
echo ""
echo "ALTERNATIVE: If you want to use SSH instead of HTTPS:"
echo ""
echo "git remote add origin git@github.com:YOUR_GITHUB_USERNAME/SoftwareRouter.git"
echo "git push -u origin Dev"
echo ""
echo "========================================="
echo ""
echo "After pushing, your repository will be available at:"
echo "https://github.com/YOUR_GITHUB_USERNAME/SoftwareRouter"
echo ""
echo "Default branch will be 'Dev' as requested."
echo ""
echo "========================================="
echo "Quick Reference Commands:"
echo "========================================="
echo ""
echo "# View current status"
echo "git status"
echo ""
echo "# View commit history"
echo "git log --oneline"
echo ""
echo "# View remote configuration"
echo "git remote -v"
echo ""
echo "# Future updates - add, commit, and push"
echo "git add ."
echo "git commit -m 'Your commit message'"
echo "git push origin Dev"
echo ""
