package main

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"strings"
)

const (
	radvdConfigPath  = "/etc/radvd.conf"
	radvdStorePath   = "/etc/softrouter/radvd_config.json"
	radvdServiceName = "radvd"
)

// RADVDConfig represents Router Advertisement configuration for an interface
type RADVDConfig struct {
	Interface  string   `json:"interface"`
	Enabled    bool     `json:"enabled"`
	Prefix     string   `json:"prefix"`     // e.g., "2001:db8::/64"
	DNSServers []string `json:"dnsServers"` // e.g., ["2001:4860:4860::8888"]
}

// RADVDStore stores RA configurations for all interfaces
type RADVDStore struct {
	Interfaces map[string]RADVDConfig `json:"interfaces"`
}

// loadRADVDConfig loads the RA configuration from disk
func loadRADVDConfig() (*RADVDStore, error) {
	store := &RADVDStore{
		Interfaces: make(map[string]RADVDConfig),
	}

	data, err := os.ReadFile(radvdStorePath)
	if err != nil {
		if os.IsNotExist(err) {
			return store, nil
		}
		return nil, err
	}

	if err := json.Unmarshal(data, store); err != nil {
		return nil, err
	}

	return store, nil
}

// saveRADVDConfig saves the RA configuration to disk
func saveRADVDConfig(store *RADVDStore) error {
	data, err := json.MarshalIndent(store, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(radvdStorePath, data, 0644)
}

// generateRADVDConfig generates /etc/radvd.conf from the stored configuration
func generateRADVDConfig() error {
	store, err := loadRADVDConfig()
	if err != nil {
		return fmt.Errorf("failed to load RA config: %w", err)
	}

	var configLines []string
	configLines = append(configLines, "# Generated by SoftRouter - DO NOT EDIT MANUALLY")
	configLines = append(configLines, "")

	// Generate configuration for each enabled interface
	for ifaceName, config := range store.Interfaces {
		if !config.Enabled {
			continue
		}

		if config.Prefix == "" {
			fmt.Printf("Warning: Interface %s has RA enabled but no prefix configured, skipping\n", ifaceName)
			continue
		}

		configLines = append(configLines, fmt.Sprintf("interface %s {", ifaceName))
		configLines = append(configLines, "    AdvSendAdvert on;")
		configLines = append(configLines, "    MinRtrAdvInterval 3;")
		configLines = append(configLines, "    MaxRtrAdvInterval 10;")
		configLines = append(configLines, "    AdvManagedFlag off;") // SLAAC, not DHCPv6
		configLines = append(configLines, "    AdvOtherConfigFlag off;")
		configLines = append(configLines, "")
		configLines = append(configLines, fmt.Sprintf("    prefix %s {", config.Prefix))
		configLines = append(configLines, "        AdvOnLink on;")
		configLines = append(configLines, "        AdvAutonomous on;")
		configLines = append(configLines, "        AdvRouterAddr on;")
		configLines = append(configLines, "    };")

		// Add DNS servers if configured
		if len(config.DNSServers) > 0 {
			configLines = append(configLines, "")
			dnsLine := "    RDNSS " + strings.Join(config.DNSServers, " ") + " {"
			configLines = append(configLines, dnsLine)
			configLines = append(configLines, "    };")
		}

		configLines = append(configLines, "};")
		configLines = append(configLines, "")
	}

	// Write config file
	configContent := strings.Join(configLines, "\n")
	if err := os.WriteFile(radvdConfigPath, []byte(configContent), 0644); err != nil {
		return fmt.Errorf("failed to write radvd config: %w", err)
	}

	fmt.Printf("Generated radvd config with %d enabled interface(s)\n", len(store.Interfaces))
	return nil
}

// reloadRADVD reloads the radvd service
func reloadRADVD() error {
	// Check if radvd is installed
	if _, err := exec.LookPath("radvd"); err != nil {
		return fmt.Errorf("radvd is not installed")
	}

	// Reload radvd service
	cmd := exec.Command("systemctl", "reload-or-restart", radvdServiceName)
	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("failed to reload radvd: %v, output: %s", err, string(output))
	}

	return nil
}

// startRADVD starts the radvd service
func startRADVD() error {
	cmd := exec.Command("systemctl", "start", radvdServiceName)
	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("failed to start radvd: %v, output: %s", err, string(output))
	}
	return nil
}

// stopRADVD stops the radvd service
func stopRADVD() error {
	cmd := exec.Command("systemctl", "stop", radvdServiceName)
	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("failed to stop radvd: %v, output: %s", err, string(output))
	}
	return nil
}

// enableRADVDService enables radvd to start on boot
func enableRADVDService() error {
	cmd := exec.Command("systemctl", "enable", radvdServiceName)
	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("failed to enable radvd: %v, output: %s", err, string(output))
	}
	return nil
}

// getRADVDStatus returns the status of the radvd service
func getRADVDStatus() (bool, error) {
	cmd := exec.Command("systemctl", "is-active", radvdServiceName)
	output, err := cmd.CombinedOutput()

	status := strings.TrimSpace(string(output))
	isRunning := (err == nil && status == "active")

	return isRunning, nil
}
