package main

import (
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"os"
	"sync"
)

type UPnPConfig struct {
	Enabled      bool   `json:"enabled"`
	EnableUPnP   bool   `json:"enable_upnp"`
	EnableNATPMP bool   `json:"enable_nat_pmp"`
	SecureMode   bool   `json:"secure_mode"` // Only forward to requesting IP
}

var (
	upnpMu        sync.RWMutex
	upnpConfig    UPnPConfig
	upnpCfgFile   = "/etc/softrouter/upnp.json"
	miniupnpdConf = "/etc/miniupnpd/miniupnpd.conf"
)

func initUPnP() {
	if err := loadUPnPConfig(); err != nil {
		log.Printf("[UPNP] No config found, creating default")
		upnpConfig = UPnPConfig{
			Enabled:      false,
			EnableUPnP:   true,
			EnableNATPMP: true,
			SecureMode:   true,
		}
		saveUPnPConfig()
	}

	applyUPnPConfig(upnpConfig)
}

func loadUPnPConfig() error {
	upnpMu.Lock()
	defer upnpMu.Unlock()

	data, err := os.ReadFile(upnpCfgFile)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, &upnpConfig)
}

func saveUPnPConfig() error {
	upnpMu.Lock()
	defer upnpMu.Unlock()

	data, err := json.MarshalIndent(upnpConfig, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(upnpCfgFile, data, 0600)
}

// generateMiniUPnPdConf creates the /etc/miniupnpd/miniupnpd.conf string
func generateMiniUPnPdConf() (string, error) {
	// Find WAN and LAN interfaces
	metaStore, _ := loadInterfaceMetadata()
	var extIf string
	var lanIf string

	hasExplicitWan := false
	for iface, m := range metaStore.Metadata {
		if m.Label == "WAN" {
			extIf = iface
			hasExplicitWan = true
		} else if m.Label == "LAN" {
			lanIf = iface
		}
	}

	if !hasExplicitWan {
		defWan, err := getDefaultGatewayInterface()
		if err == nil && defWan != "" {
			extIf = defWan
		}
	}

	if extIf == "" || lanIf == "" {
		return "", fmt.Errorf("could not determine WAN or LAN interface for UPnP")
	}

	conf := fmt.Sprintf(`
# miniupnpd configuration generated by SoftwareRouter

ext_ifname=%s
listening_ip=%s
port=5000

enable_upnp=%s
enable_natpmp=%s

secure_mode=%s

system_uptime=yes

# Default rules (allow higher ports)
allow 1024-65535 192.168.0.0/16 1024-65535
allow 1024-65535 10.0.0.0/8 1024-65535
allow 1024-65535 172.16.0.0/12 1024-65535
deny 0-65535 0.0.0.0/0 0-65535
    `,
		extIf, lanIf,
		boolToStr(upnpConfig.EnableUPnP),
		boolToStr(upnpConfig.EnableNATPMP),
		boolToStr(upnpConfig.SecureMode))

	return conf, nil
}

func boolToStr(b bool) string {
	if b {
		return "yes"
	}
	return "no"
}

func applyUPnPConfig(cfg UPnPConfig) error {
	if !cfg.Enabled {
		// Stop and disable service
		runPrivileged("systemctl", "stop", "miniupnpd")
		runPrivileged("systemctl", "disable", "miniupnpd")
		return nil
	}

	// Generate custom config
	confStr, err := generateMiniUPnPdConf()
	if err != nil {
		log.Printf("[UPNP] Error generating config: %v", err)
		return err
	}

	// Write config to temp file then privileged-copy to final location
	err = os.WriteFile("/tmp/miniupnpd.conf", []byte(confStr), 0644)
	if err == nil {
		runPrivileged("cp", "/tmp/miniupnpd.conf", miniupnpdConf)
	}

	runPrivileged("systemctl", "enable", "miniupnpd")
	return runPrivileged("systemctl", "restart", "miniupnpd")
}

// Handlers
func getUPnPConfigHandler(w http.ResponseWriter, r *http.Request) {
	upnpMu.RLock()
	defer upnpMu.RUnlock()

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(upnpConfig)
}

func updateUPnPConfigHandler(w http.ResponseWriter, r *http.Request) {
	var newCfg UPnPConfig
	if err := json.NewDecoder(r.Body).Decode(&newCfg); err != nil {
		respondWithError(w, ErrGenericInvalidRequest, "Invalid configuration format", http.StatusBadRequest, err)
		return
	}

	upnpMu.Lock()
	upnpConfig = newCfg
	upnpMu.Unlock()

	if err := saveUPnPConfig(); err != nil {
		respondWithError(w, ErrSystemConfigSave, "Failed to save UPnP configuration", http.StatusInternalServerError, err)
		return
	}

	if err := applyUPnPConfig(newCfg); err != nil {
		respondWithError(w, ErrSystemServiceControl, "Failed to apply UPnP configuration", http.StatusInternalServerError, err)
		return
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(map[string]string{"status": "success"})
}
